# Indonesian translations for PROJECT.
# Copyright (C) 2019 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2019.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2019-03-01 16:00+0500\n"
"PO-Revision-Date: 2019-03-01 16:01+0500\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: id\n"
"Language-Team: id <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.5.0\n"

#: app/api/v1/requests/args_validation.py:35
msgid "imei too short, should contain at least {min} characters"
msgstr ""

#: app/api/v1/requests/args_validation.py:38
msgid "imei too long, cannot contain more than {max} characters"
msgstr ""

#: app/api/v1/requests/args_validation.py:41
msgid "invalid imei"
msgstr ""

#: app/api/v1/requests/args_validation.py:48
msgid "invalid msisdn"
msgstr ""

#: app/api/v1/resources/admin.py:69
msgid "message"
msgstr ""

#: app/api/v1/resources/admin.py:69
msgid "Failed to retrieve IMEI response from core system."
msgstr ""

#: app/api/v1/resources/admin.py:83
msgid "Error generating IMEI response. Check dirbs core url."
msgstr ""

#: app/api/v1/resources/admin.py:143
msgid "Error generating MSISDN response. Check dirbs core url."
msgstr ""

#: app/api/v1/resources/case.py:56 app/api/v1/resources/case.py:123
#: app/api/v1/resources/case.py:172 app/api/v1/resources/case.py:387
msgid "Case not found"
msgstr ""

#: app/api/v1/resources/case.py:76
msgid ""
"Error retrieving case results. Please check tracking id or database "
"connection."
msgstr ""

#: app/api/v1/resources/case.py:92 app/api/v1/resources/case.py:372
msgid "Case updation not allowed in this status"
msgstr ""

#: app/api/v1/resources/case.py:102 app/api/v1/resources/case.py:324
msgid "Enter at least one optional field with full name in personal details."
msgstr ""

#: app/api/v1/resources/case.py:112
msgid "Case updated successfully"
msgstr ""

#: app/api/v1/resources/case.py:133
msgid "Case update failed!"
msgstr ""

#: app/api/v1/resources/case.py:149
msgid ""
"Unable to update case status. Either Blocking is disabled or case has "
"already been recovered."
msgstr ""

#: app/api/v1/resources/case.py:157
msgid "Case already has the same status."
msgstr ""

#: app/api/v1/resources/case.py:164 app/api/v1/resources/case.py:379
msgid "Case status updated"
msgstr ""

#: app/api/v1/resources/case.py:182
msgid "Case status update failed!"
msgstr ""

#: app/api/v1/resources/case.py:333
msgid "case successfully added"
msgstr ""

#: app/api/v1/resources/case.py:342 app/api/v1/resources/case.py:353
msgid "case addition failed"
msgstr ""

#: app/api/v1/resources/case.py:397
msgid "Update of case information failed!"
msgstr ""

#: app/api/v1/resources/common.py:40
msgid "Welcome to LSDS"
msgstr ""

#: app/api/v1/resources/common.py:57
msgid "CORE connected successfully."
msgstr ""

#: app/api/v1/resources/common.py:61 app/api/v1/resources/common.py:65
msgid "CORE connection failed."
msgstr ""

#: app/api/v1/resources/common.py:69
msgid "Database connected successfully"
msgstr ""

#: app/api/v1/resources/common.py:71
msgid "Database connection failed"
msgstr ""

#: app/api/v1/resources/search.py:142
msgid "service unavailable"
msgstr ""

#: app/api/v1/resources/system.py:57 app/api/v1/resources/system.py:82
msgid "Database connectivity error. Please check connection parameters."
msgstr ""

#: app/api/v1/schema/validations.py:11
msgid "name should contain more than one character"
msgstr ""

#: app/api/v1/schema/validations.py:13
msgid "name cannot contain more than 1000 characters"
msgstr ""

#: app/api/v1/schema/validations.py:15
msgid "Name cannot contain invalid characters"
msgstr ""

#: app/api/v1/schema/validations.py:22
msgid "Comment should contain more than one character"
msgstr ""

#: app/api/v1/schema/validations.py:24
msgid "Comment cannot contain more than 1000 characters"
msgstr ""

#: app/api/v1/schema/validations.py:26
msgid "Comment cannot have invalid characters"
msgstr ""

#: app/api/v1/schema/validations.py:33
msgid "Alternate phone number is invalid."
msgstr ""

#: app/api/v1/schema/validations.py:40
msgid "Invalid date format"
msgstr ""

#: app/api/v1/schema/validations.py:47
msgid "IMEI too short, should contain at least {min} characters"
msgstr ""

#: app/api/v1/schema/validations.py:49
msgid "IMEI too long, cannot contain more than {max} characters"
msgstr ""

#: app/api/v1/schema/validations.py:51
msgid "IMEI is invalid."
msgstr ""

#: app/api/v1/schema/validations.py:58
msgid "MSISDN is invalid."
msgstr ""

#: app/api/v1/schema/validations.py:65
msgid "Government Identification Number must contain {range} digits"
msgstr ""

#: app/api/v1/schema/validations.py:71
msgid "{field} should contain at least {min} character"
msgstr ""

#: app/api/v1/schema/validations.py:73
msgid "{field} cannot contain more than {max} characters"
msgstr ""

